[package]
name = "omma"
version = "1.0.7"
edition = "2024"

[[bin]]
name = "omma"
path = "src/main.rs"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_12"] }
libadwaita = { version = "0.7", features = ["v1_6"] }
