name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ARM64 binary
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          fedora:latest \
          bash -c '
            set -e
            dnf install -y gtk4-devel gcc libadwaita-devel curl
            curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            cargo build --release
            strip target/release/omma
          '

    - name: Prepare artifact
      run: |
        mkdir -p dist
        cp target/release/omma dist/omma-aarch64-unknown-linux-gnu
        chmod +x dist/omma-aarch64-unknown-linux-gnu
        ls -lh dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/omma-aarch64-unknown-linux-gnu
        body: |
          ## Omma Linux ${{ github.ref_name }}

          **ARM64 build for Raspberry Pi 3/4/5 with 64-bit OS**

          ### Installation on Your Pi

          ```bash
          # Install dependencies (one-time)
          sudo apt-get update
          sudo apt-get install -y libgtk-4-1 libadwaita-1-0

          # Download the binary
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/omma-aarch64-unknown-linux-gnu

          # Make it executable
          chmod +x omma-aarch64-unknown-linux-gnu

          # Move to system path
          sudo mv omma-aarch64-unknown-linux-gnu /usr/local/bin/omma

          # Run it
          omma
          ```

          ### Build Details
          - **Platform**: ARM64 (aarch64-unknown-linux-gnu)
          - **Built with**: Fedora Docker image + QEMU
          - **Binary size**: ~450KB
          - **Runtime memory**: ~30MB RAM

          ### Features
          - Incubator management UI
          - Task tracking system
          - Real-time search and filtering
          - Native GTK4/libadwaita performance
          - Dark mode optimized for Pi displays

          ---
          🤖 Built automatically by GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
